#pragma once

#include <array>
#include <stdexcept>
#include <string>
#include <unordered_map>

#include "BlockId.hpp"

namespace onion::voxel
{
	class BlockIds
	{
		// ----- Static Methods -----
	  public:
		static int GetBlockIdCount() { return static_cast<int>(BlockId::Count); }

		static const std::string& GetName(BlockId id) { return s_IdToName[static_cast<size_t>(id)]; }

		static BlockId GetId(const std::string& name)
		{
			const auto& map = GetNameToId();
			auto it = map.find(name);
			if (it == map.end())
				throw std::runtime_error("Unknown block name: " + name);
			return it->second;
		}

		// ----- Static Members -----
	  private:
		static inline std::array<std::string, static_cast<size_t>(BlockId::Count)> s_IdToName = {
			"Air",
			"Snow Grass Block",
			"Acacia Button",
			"Acacia Door",
			"Acacia Fence",
			"Acacia Fence Gate",
			"Acacia Hanging Sign",
			"Acacia Leaves",
			"Acacia Log",
			"Acacia Planks",
			"Acacia Pressure Plate",
			"Acacia Sapling",
			"Acacia Shelf",
			"Acacia Sign",
			"Acacia Slab",
			"Acacia Stairs",
			"Acacia Trapdoor",
			"Acacia Wall Hanging Sign",
			"Acacia Wall Sign",
			"Acacia Wood",
			"Activator Rail",
			"Allium",
			"Amethyst Block",
			"Amethyst Cluster",
			"Ancient Debris",
			"Andesite",
			"Andesite Slab",
			"Andesite Stairs",
			"Andesite Wall",
			"Anvil",
			"Attached Melon Stem",
			"Attached Pumpkin Stem",
			"Azalea",
			"Azalea Leaves",
			"Azure Bluet",
			"Bamboo",
			"Bamboo Block",
			"Bamboo Button",
			"Bamboo Door",
			"Bamboo Fence",
			"Bamboo Fence Gate",
			"Bamboo Hanging Sign",
			"Bamboo Mosaic",
			"Bamboo Mosaic Slab",
			"Bamboo Mosaic Stairs",
			"Bamboo Planks",
			"Bamboo Pressure Plate",
			"Bamboo Sapling",
			"Bamboo Shelf",
			"Bamboo Sign",
			"Bamboo Slab",
			"Bamboo Stairs",
			"Bamboo Trapdoor",
			"Bamboo Wall Hanging Sign",
			"Bamboo Wall Sign",
			"Barrel",
			"Barrier",
			"Basalt",
			"Beacon",
			"Bedrock",
			"Beehive",
			"Bee Nest",
			"Beetroots",
			"Bell",
			"Big Dripleaf",
			"Big Dripleaf Stem",
			"Birch Button",
			"Birch Door",
			"Birch Fence",
			"Birch Fence Gate",
			"Birch Hanging Sign",
			"Birch Leaves",
			"Birch Log",
			"Birch Planks",
			"Birch Pressure Plate",
			"Birch Sapling",
			"Birch Shelf",
			"Birch Sign",
			"Birch Slab",
			"Birch Stairs",
			"Birch Trapdoor",
			"Birch Wall Hanging Sign",
			"Birch Wall Sign",
			"Birch Wood",
			"Black Banner",
			"Black Bed",
			"Black Candle",
			"Black Candle Cake",
			"Black Carpet",
			"Black Concrete",
			"Black Concrete Powder",
			"Black Glazed Terracotta",
			"Black Shulker Box",
			"Black Stained Glass",
			"Black Stained Glass Pane",
			"Blackstone",
			"Blackstone Slab",
			"Blackstone Stairs",
			"Blackstone Wall",
			"Black Terracotta",
			"Black Wall Banner",
			"Black Wool",
			"Blast Furnace",
			"Blue Banner",
			"Blue Bed",
			"Blue Candle",
			"Blue Candle Cake",
			"Blue Carpet",
			"Blue Concrete",
			"Blue Concrete Powder",
			"Blue Glazed Terracotta",
			"Blue Ice",
			"Blue Orchid",
			"Blue Shulker Box",
			"Blue Stained Glass",
			"Blue Stained Glass Pane",
			"Blue Terracotta",
			"Blue Wall Banner",
			"Blue Wool",
			"Bone Block",
			"Bookshelf",
			"Brain Coral",
			"Brain Coral Block",
			"Brain Coral Fan",
			"Brain Coral Wall Fan",
			"Brewing Stand",
			"Bricks",
			"Brick Slab",
			"Brick Stairs",
			"Brick Wall",
			"Brown Banner",
			"Brown Bed",
			"Brown Candle",
			"Brown Candle Cake",
			"Brown Carpet",
			"Brown Concrete",
			"Brown Concrete Powder",
			"Brown Glazed Terracotta",
			"Brown Mushroom",
			"Brown Mushroom Block",
			"Brown Shulker Box",
			"Brown Stained Glass",
			"Brown Stained Glass Pane",
			"Brown Terracotta",
			"Brown Wall Banner",
			"Brown Wool",
			"Bubble Column",
			"Bubble Coral",
			"Bubble Coral Block",
			"Bubble Coral Fan",
			"Bubble Coral Wall Fan",
			"Budding Amethyst",
			"Bush",
			"Cactus",
			"Cactus Flower",
			"Cake",
			"Calcite",
			"Calibrated Sculk Sensor",
			"Campfire",
			"Candle",
			"Candle Cake",
			"Carrots",
			"Cartography Table",
			"Carved Pumpkin",
			"Cauldron",
			"Cave Air",
			"Cave Vines",
			"Cave Vines Plant",
			"Chain Command Block",
			"Cherry Button",
			"Cherry Door",
			"Cherry Fence",
			"Cherry Fence Gate",
			"Cherry Hanging Sign",
			"Cherry Leaves",
			"Cherry Log",
			"Cherry Planks",
			"Cherry Pressure Plate",
			"Cherry Sapling",
			"Cherry Shelf",
			"Cherry Sign",
			"Cherry Slab",
			"Cherry Stairs",
			"Cherry Trapdoor",
			"Cherry Wall Hanging Sign",
			"Cherry Wall Sign",
			"Cherry Wood",
			"Chest",
			"Chipped Anvil",
			"Chiseled Bookshelf",
			"Chiseled Copper",
			"Chiseled Deepslate",
			"Chiseled Nether Bricks",
			"Chiseled Polished Blackstone",
			"Chiseled Quartz Block",
			"Chiseled Red Sandstone",
			"Chiseled Resin Bricks",
			"Chiseled Sandstone",
			"Chiseled Stone Bricks",
			"Chiseled Tuff",
			"Chiseled Tuff Bricks",
			"Chorus Flower",
			"Chorus Plant",
			"Clay",
			"Closed Eyeblossom",
			"Coal Block",
			"Coal Ore",
			"Coarse Dirt",
			"Cobbled Deepslate",
			"Cobbled Deepslate Slab",
			"Cobbled Deepslate Stairs",
			"Cobbled Deepslate Wall",
			"Cobblestone",
			"Cobblestone Slab",
			"Cobblestone Stairs",
			"Cobblestone Wall",
			"Cobweb",
			"Cocoa",
			"Command Block",
			"Comparator",
			"Composter",
			"Conduit",
			"Copper Bars",
			"Copper Block",
			"Copper Bulb",
			"Copper Chain",
			"Copper Chest",
			"Copper Door",
			"Copper Golem Statue",
			"Copper Grate",
			"Copper Lantern",
			"Copper Ore",
			"Copper Torch",
			"Copper Trapdoor",
			"Copper Wall Torch",
			"Cornflower",
			"Cracked Deepslate Bricks",
			"Cracked Deepslate Tiles",
			"Cracked Nether Bricks",
			"Cracked Polished Blackstone Bricks",
			"Cracked Stone Bricks",
			"Crafter",
			"Crafting Table",
			"Creaking Heart",
			"Creeper Head",
			"Creeper Wall Head",
			"Crimson Button",
			"Crimson Door",
			"Crimson Fence",
			"Crimson Fence Gate",
			"Crimson Fungus",
			"Crimson Hanging Sign",
			"Crimson Hyphae",
			"Crimson Nylium",
			"Crimson Planks",
			"Crimson Pressure Plate",
			"Crimson Roots",
			"Crimson Shelf",
			"Crimson Sign",
			"Crimson Slab",
			"Crimson Stairs",
			"Crimson Stem",
			"Crimson Trapdoor",
			"Crimson Wall Hanging Sign",
			"Crimson Wall Sign",
			"Crying Obsidian",
			"Cut Copper",
			"Cut Copper Slab",
			"Cut Copper Stairs",
			"Cut Red Sandstone",
			"Cut Red Sandstone Slab",
			"Cut Sandstone",
			"Cut Sandstone Slab",
			"Cyan Banner",
			"Cyan Bed",
			"Cyan Candle",
			"Cyan Candle Cake",
			"Cyan Carpet",
			"Cyan Concrete",
			"Cyan Concrete Powder",
			"Cyan Glazed Terracotta",
			"Cyan Shulker Box",
			"Cyan Stained Glass",
			"Cyan Stained Glass Pane",
			"Cyan Terracotta",
			"Cyan Wall Banner",
			"Cyan Wool",
			"Damaged Anvil",
			"Dandelion",
			"Dark Oak Button",
			"Dark Oak Door",
			"Dark Oak Fence",
			"Dark Oak Fence Gate",
			"Dark Oak Hanging Sign",
			"Dark Oak Leaves",
			"Dark Oak Log",
			"Dark Oak Planks",
			"Dark Oak Pressure Plate",
			"Dark Oak Sapling",
			"Dark Oak Shelf",
			"Dark Oak Sign",
			"Dark Oak Slab",
			"Dark Oak Stairs",
			"Dark Oak Trapdoor",
			"Dark Oak Wall Hanging Sign",
			"Dark Oak Wall Sign",
			"Dark Oak Wood",
			"Dark Prismarine",
			"Dark Prismarine Slab",
			"Dark Prismarine Stairs",
			"Daylight Detector",
			"Dead Brain Coral",
			"Dead Brain Coral Block",
			"Dead Brain Coral Fan",
			"Dead Brain Coral Wall Fan",
			"Dead Bubble Coral",
			"Dead Bubble Coral Block",
			"Dead Bubble Coral Fan",
			"Dead Bubble Coral Wall Fan",
			"Dead Bush",
			"Dead Fire Coral",
			"Dead Fire Coral Block",
			"Dead Fire Coral Fan",
			"Dead Fire Coral Wall Fan",
			"Dead Horn Coral",
			"Dead Horn Coral Block",
			"Dead Horn Coral Fan",
			"Dead Horn Coral Wall Fan",
			"Dead Tube Coral",
			"Dead Tube Coral Block",
			"Dead Tube Coral Fan",
			"Dead Tube Coral Wall Fan",
			"Decorated Pot",
			"Deepslate",
			"Deepslate Bricks",
			"Deepslate Brick Slab",
			"Deepslate Brick Stairs",
			"Deepslate Brick Wall",
			"Deepslate Coal Ore",
			"Deepslate Copper Ore",
			"Deepslate Diamond Ore",
			"Deepslate Emerald Ore",
			"Deepslate Gold Ore",
			"Deepslate Iron Ore",
			"Deepslate Lapis Ore",
			"Deepslate Redstone Ore",
			"Deepslate Tiles",
			"Deepslate Tile Slab",
			"Deepslate Tile Stairs",
			"Deepslate Tile Wall",
			"Detector Rail",
			"Diamond Block",
			"Diamond Ore",
			"Diorite",
			"Diorite Slab",
			"Diorite Stairs",
			"Diorite Wall",
			"Dirt",
			"Dirt Path",
			"Dispenser",
			"Dragon Egg",
			"Dragon Head",
			"Dragon Wall Head",
			"Dried Ghast",
			"Dried Kelp Block",
			"Dripstone Block",
			"Dropper",
			"Emerald Block",
			"Emerald Ore",
			"Enchanting Table",
			"Ender Chest",
			"End Gateway",
			"End Portal",
			"End Portal Frame",
			"End Rod",
			"End Stone",
			"End Stone Bricks",
			"End Stone Brick Slab",
			"End Stone Brick Stairs",
			"End Stone Brick Wall",
			"Exposed Chiseled Copper",
			"Exposed Copper",
			"Exposed Copper Bars",
			"Exposed Copper Bulb",
			"Exposed Copper Chain",
			"Exposed Copper Chest",
			"Exposed Copper Door",
			"Exposed Copper Golem Statue",
			"Exposed Copper Grate",
			"Exposed Copper Lantern",
			"Exposed Copper Trapdoor",
			"Exposed Cut Copper",
			"Exposed Cut Copper Slab",
			"Exposed Cut Copper Stairs",
			"Exposed Lightning Rod",
			"Farmland",
			"Fern",
			"Fire",
			"Fire Coral",
			"Fire Coral Block",
			"Fire Coral Fan",
			"Fire Coral Wall Fan",
			"Firefly Bush",
			"Fletching Table",
			"Flowering Azalea",
			"Flowering Azalea Leaves",
			"Flower Pot",
			"Frogspawn",
			"Frosted Ice",
			"Furnace",
			"Gilded Blackstone",
			"Glass",
			"Glass Pane",
			"Glow Item Frame",
			"Glow Lichen",
			"Glowstone",
			"Gold Block",
			"Gold Ore",
			"Granite",
			"Granite Slab",
			"Granite Stairs",
			"Granite Wall",
			"Grass Block",
			"Gravel",
			"Gray Banner",
			"Gray Bed",
			"Gray Candle",
			"Gray Candle Cake",
			"Gray Carpet",
			"Gray Concrete",
			"Gray Concrete Powder",
			"Gray Glazed Terracotta",
			"Gray Shulker Box",
			"Gray Stained Glass",
			"Gray Stained Glass Pane",
			"Gray Terracotta",
			"Gray Wall Banner",
			"Gray Wool",
			"Green Banner",
			"Green Bed",
			"Green Candle",
			"Green Candle Cake",
			"Green Carpet",
			"Green Concrete",
			"Green Concrete Powder",
			"Green Glazed Terracotta",
			"Green Shulker Box",
			"Green Stained Glass",
			"Green Stained Glass Pane",
			"Green Terracotta",
			"Green Wall Banner",
			"Green Wool",
			"Grindstone",
			"Hanging Roots",
			"Hay Block",
			"Heavy Core",
			"Heavy Weighted Pressure Plate",
			"Honey Block",
			"Honeycomb Block",
			"Hopper",
			"Horn Coral",
			"Horn Coral Block",
			"Horn Coral Fan",
			"Horn Coral Wall Fan",
			"Ice",
			"Infested Chiseled Stone Bricks",
			"Infested Cobblestone",
			"Infested Cracked Stone Bricks",
			"Infested Deepslate",
			"Infested Mossy Stone Bricks",
			"Infested Stone",
			"Infested Stone Bricks",
			"Iron Bars",
			"Iron Block",
			"Iron Chain",
			"Iron Door",
			"Iron Ore",
			"Iron Trapdoor",
			"Item Frame",
			"Jack O Lantern",
			"Jigsaw",
			"Jukebox",
			"Jungle Button",
			"Jungle Door",
			"Jungle Fence",
			"Jungle Fence Gate",
			"Jungle Hanging Sign",
			"Jungle Leaves",
			"Jungle Log",
			"Jungle Planks",
			"Jungle Pressure Plate",
			"Jungle Sapling",
			"Jungle Shelf",
			"Jungle Sign",
			"Jungle Slab",
			"Jungle Stairs",
			"Jungle Trapdoor",
			"Jungle Wall Hanging Sign",
			"Jungle Wall Sign",
			"Jungle Wood",
			"Kelp",
			"Kelp Plant",
			"Ladder",
			"Lantern",
			"Lapis Block",
			"Lapis Ore",
			"Large Amethyst Bud",
			"Large Fern",
			"Lava",
			"Lava Cauldron",
			"Leaf Litter",
			"Lectern",
			"Lever",
			"Light",
			"Light Blue Banner",
			"Light Blue Bed",
			"Light Blue Candle",
			"Light Blue Candle Cake",
			"Light Blue Carpet",
			"Light Blue Concrete",
			"Light Blue Concrete Powder",
			"Light Blue Glazed Terracotta",
			"Light Blue Shulker Box",
			"Light Blue Stained Glass",
			"Light Blue Stained Glass Pane",
			"Light Blue Terracotta",
			"Light Blue Wall Banner",
			"Light Blue Wool",
			"Light Gray Banner",
			"Light Gray Bed",
			"Light Gray Candle",
			"Light Gray Candle Cake",
			"Light Gray Carpet",
			"Light Gray Concrete",
			"Light Gray Concrete Powder",
			"Light Gray Glazed Terracotta",
			"Light Gray Shulker Box",
			"Light Gray Stained Glass",
			"Light Gray Stained Glass Pane",
			"Light Gray Terracotta",
			"Light Gray Wall Banner",
			"Light Gray Wool",
			"Lightning Rod",
			"Light Weighted Pressure Plate",
			"Lilac",
			"Lily Of The Valley",
			"Lily Pad",
			"Lime Banner",
			"Lime Bed",
			"Lime Candle",
			"Lime Candle Cake",
			"Lime Carpet",
			"Lime Concrete",
			"Lime Concrete Powder",
			"Lime Glazed Terracotta",
			"Lime Shulker Box",
			"Lime Stained Glass",
			"Lime Stained Glass Pane",
			"Lime Terracotta",
			"Lime Wall Banner",
			"Lime Wool",
			"Lodestone",
			"Loom",
			"Magenta Banner",
			"Magenta Bed",
			"Magenta Candle",
			"Magenta Candle Cake",
			"Magenta Carpet",
			"Magenta Concrete",
			"Magenta Concrete Powder",
			"Magenta Glazed Terracotta",
			"Magenta Shulker Box",
			"Magenta Stained Glass",
			"Magenta Stained Glass Pane",
			"Magenta Terracotta",
			"Magenta Wall Banner",
			"Magenta Wool",
			"Magma Block",
			"Mangrove Button",
			"Mangrove Door",
			"Mangrove Fence",
			"Mangrove Fence Gate",
			"Mangrove Hanging Sign",
			"Mangrove Leaves",
			"Mangrove Log",
			"Mangrove Planks",
			"Mangrove Pressure Plate",
			"Mangrove Propagule",
			"Mangrove Roots",
			"Mangrove Shelf",
			"Mangrove Sign",
			"Mangrove Slab",
			"Mangrove Stairs",
			"Mangrove Trapdoor",
			"Mangrove Wall Hanging Sign",
			"Mangrove Wall Sign",
			"Mangrove Wood",
			"Medium Amethyst Bud",
			"Melon",
			"Melon Stem",
			"Moss Block",
			"Moss Carpet",
			"Mossy Cobblestone",
			"Mossy Cobblestone Slab",
			"Mossy Cobblestone Stairs",
			"Mossy Cobblestone Wall",
			"Mossy Stone Bricks",
			"Mossy Stone Brick Slab",
			"Mossy Stone Brick Stairs",
			"Mossy Stone Brick Wall",
			"Moving Piston",
			"Mud",
			"Mud Bricks",
			"Mud Brick Slab",
			"Mud Brick Stairs",
			"Mud Brick Wall",
			"Muddy Mangrove Roots",
			"Mushroom Stem",
			"Mycelium",
			"Nether Brick Fence",
			"Nether Bricks",
			"Nether Brick Slab",
			"Nether Brick Stairs",
			"Nether Brick Wall",
			"Nether Gold Ore",
			"Netherite Block",
			"Nether Portal",
			"Nether Quartz Ore",
			"Netherrack",
			"Nether Sprouts",
			"Nether Wart",
			"Nether Wart Block",
			"Note Block",
			"Oak Button",
			"Oak Door",
			"Oak Fence",
			"Oak Fence Gate",
			"Oak Hanging Sign",
			"Oak Leaves",
			"Oak Log",
			"Oak Planks",
			"Oak Pressure Plate",
			"Oak Sapling",
			"Oak Shelf",
			"Oak Sign",
			"Oak Slab",
			"Oak Stairs",
			"Oak Trapdoor",
			"Oak Wall Hanging Sign",
			"Oak Wall Sign",
			"Oak Wood",
			"Observer",
			"Obsidian",
			"Ochre Froglight",
			"Open Eyeblossom",
			"Orange Banner",
			"Orange Bed",
			"Orange Candle",
			"Orange Candle Cake",
			"Orange Carpet",
			"Orange Concrete",
			"Orange Concrete Powder",
			"Orange Glazed Terracotta",
			"Orange Shulker Box",
			"Orange Stained Glass",
			"Orange Stained Glass Pane",
			"Orange Terracotta",
			"Orange Tulip",
			"Orange Wall Banner",
			"Orange Wool",
			"Oxeye Daisy",
			"Oxidized Chiseled Copper",
			"Oxidized Copper",
			"Oxidized Copper Bars",
			"Oxidized Copper Bulb",
			"Oxidized Copper Chain",
			"Oxidized Copper Chest",
			"Oxidized Copper Door",
			"Oxidized Copper Golem Statue",
			"Oxidized Copper Grate",
			"Oxidized Copper Lantern",
			"Oxidized Copper Trapdoor",
			"Oxidized Cut Copper",
			"Oxidized Cut Copper Slab",
			"Oxidized Cut Copper Stairs",
			"Oxidized Lightning Rod",
			"Packed Ice",
			"Packed Mud",
			"Pale Hanging Moss",
			"Pale Moss Block",
			"Pale Moss Carpet",
			"Pale Oak Button",
			"Pale Oak Door",
			"Pale Oak Fence",
			"Pale Oak Fence Gate",
			"Pale Oak Hanging Sign",
			"Pale Oak Leaves",
			"Pale Oak Log",
			"Pale Oak Planks",
			"Pale Oak Pressure Plate",
			"Pale Oak Sapling",
			"Pale Oak Shelf",
			"Pale Oak Sign",
			"Pale Oak Slab",
			"Pale Oak Stairs",
			"Pale Oak Trapdoor",
			"Pale Oak Wall Hanging Sign",
			"Pale Oak Wall Sign",
			"Pale Oak Wood",
			"Pearlescent Froglight",
			"Peony",
			"Petrified Oak Slab",
			"Piglin Head",
			"Piglin Wall Head",
			"Pink Banner",
			"Pink Bed",
			"Pink Candle",
			"Pink Candle Cake",
			"Pink Carpet",
			"Pink Concrete",
			"Pink Concrete Powder",
			"Pink Glazed Terracotta",
			"Pink Petals",
			"Pink Shulker Box",
			"Pink Stained Glass",
			"Pink Stained Glass Pane",
			"Pink Terracotta",
			"Pink Tulip",
			"Pink Wall Banner",
			"Pink Wool",
			"Piston",
			"Piston Head",
			"Pitcher Crop",
			"Pitcher Plant",
			"Player Head",
			"Player Wall Head",
			"Podzol",
			"Pointed Dripstone",
			"Polished Andesite",
			"Polished Andesite Slab",
			"Polished Andesite Stairs",
			"Polished Basalt",
			"Polished Blackstone",
			"Polished Blackstone Bricks",
			"Polished Blackstone Brick Slab",
			"Polished Blackstone Brick Stairs",
			"Polished Blackstone Brick Wall",
			"Polished Blackstone Button",
			"Polished Blackstone Pressure Plate",
			"Polished Blackstone Slab",
			"Polished Blackstone Stairs",
			"Polished Blackstone Wall",
			"Polished Deepslate",
			"Polished Deepslate Slab",
			"Polished Deepslate Stairs",
			"Polished Deepslate Wall",
			"Polished Diorite",
			"Polished Diorite Slab",
			"Polished Diorite Stairs",
			"Polished Granite",
			"Polished Granite Slab",
			"Polished Granite Stairs",
			"Polished Tuff",
			"Polished Tuff Slab",
			"Polished Tuff Stairs",
			"Polished Tuff Wall",
			"Poppy",
			"Potatoes",
			"Potted Acacia Sapling",
			"Potted Allium",
			"Potted Azalea Bush",
			"Potted Azure Bluet",
			"Potted Bamboo",
			"Potted Birch Sapling",
			"Potted Blue Orchid",
			"Potted Brown Mushroom",
			"Potted Cactus",
			"Potted Cherry Sapling",
			"Potted Closed Eyeblossom",
			"Potted Cornflower",
			"Potted Crimson Fungus",
			"Potted Crimson Roots",
			"Potted Dandelion",
			"Potted Dark Oak Sapling",
			"Potted Dead Bush",
			"Potted Fern",
			"Potted Flowering Azalea Bush",
			"Potted Jungle Sapling",
			"Potted Lily Of The Valley",
			"Potted Mangrove Propagule",
			"Potted Oak Sapling",
			"Potted Open Eyeblossom",
			"Potted Orange Tulip",
			"Potted Oxeye Daisy",
			"Potted Pale Oak Sapling",
			"Potted Pink Tulip",
			"Potted Poppy",
			"Potted Red Mushroom",
			"Potted Red Tulip",
			"Potted Spruce Sapling",
			"Potted Torchflower",
			"Potted Warped Fungus",
			"Potted Warped Roots",
			"Potted White Tulip",
			"Potted Wither Rose",
			"Powder Snow",
			"Powder Snow Cauldron",
			"Powered Rail",
			"Prismarine",
			"Prismarine Bricks",
			"Prismarine Brick Slab",
			"Prismarine Brick Stairs",
			"Prismarine Slab",
			"Prismarine Stairs",
			"Prismarine Wall",
			"Pumpkin",
			"Pumpkin Stem",
			"Purple Banner",
			"Purple Bed",
			"Purple Candle",
			"Purple Candle Cake",
			"Purple Carpet",
			"Purple Concrete",
			"Purple Concrete Powder",
			"Purple Glazed Terracotta",
			"Purple Shulker Box",
			"Purple Stained Glass",
			"Purple Stained Glass Pane",
			"Purple Terracotta",
			"Purple Wall Banner",
			"Purple Wool",
			"Purpur Block",
			"Purpur Pillar",
			"Purpur Slab",
			"Purpur Stairs",
			"Quartz Block",
			"Quartz Bricks",
			"Quartz Pillar",
			"Quartz Slab",
			"Quartz Stairs",
			"Rail",
			"Raw Copper Block",
			"Raw Gold Block",
			"Raw Iron Block",
			"Red Banner",
			"Red Bed",
			"Red Candle",
			"Red Candle Cake",
			"Red Carpet",
			"Red Concrete",
			"Red Concrete Powder",
			"Red Glazed Terracotta",
			"Red Mushroom",
			"Red Mushroom Block",
			"Red Nether Bricks",
			"Red Nether Brick Slab",
			"Red Nether Brick Stairs",
			"Red Nether Brick Wall",
			"Red Sand",
			"Red Sandstone",
			"Red Sandstone Slab",
			"Red Sandstone Stairs",
			"Red Sandstone Wall",
			"Red Shulker Box",
			"Red Stained Glass",
			"Red Stained Glass Pane",
			"Redstone Block",
			"Redstone Lamp",
			"Redstone Ore",
			"Redstone Torch",
			"Redstone Wall Torch",
			"Redstone Wire",
			"Red Terracotta",
			"Red Tulip",
			"Red Wall Banner",
			"Red Wool",
			"Reinforced Deepslate",
			"Repeater",
			"Repeating Command Block",
			"Resin Block",
			"Resin Bricks",
			"Resin Brick Slab",
			"Resin Brick Stairs",
			"Resin Brick Wall",
			"Resin Clump",
			"Respawn Anchor",
			"Rooted Dirt",
			"Rose Bush",
			"Sand",
			"Sandstone",
			"Sandstone Slab",
			"Sandstone Stairs",
			"Sandstone Wall",
			"Scaffolding",
			"Sculk",
			"Sculk Catalyst",
			"Sculk Sensor",
			"Sculk Shrieker",
			"Sculk Vein",
			"Seagrass",
			"Sea Lantern",
			"Sea Pickle",
			"Short Dry Grass",
			"Short Grass",
			"Shroomlight",
			"Shulker Box",
			"Skeleton Skull",
			"Skeleton Wall Skull",
			"Slime Block",
			"Small Amethyst Bud",
			"Small Dripleaf",
			"Smithing Table",
			"Smoker",
			"Smooth Basalt",
			"Smooth Quartz",
			"Smooth Quartz Slab",
			"Smooth Quartz Stairs",
			"Smooth Red Sandstone",
			"Smooth Red Sandstone Slab",
			"Smooth Red Sandstone Stairs",
			"Smooth Sandstone",
			"Smooth Sandstone Slab",
			"Smooth Sandstone Stairs",
			"Smooth Stone",
			"Smooth Stone Slab",
			"Sniffer Egg",
			"Snow",
			"Snow Block",
			"Soul Campfire",
			"Soul Fire",
			"Soul Lantern",
			"Soul Sand",
			"Soul Soil",
			"Soul Torch",
			"Soul Wall Torch",
			"Spawner",
			"Sponge",
			"Spore Blossom",
			"Spruce Button",
			"Spruce Door",
			"Spruce Fence",
			"Spruce Fence Gate",
			"Spruce Hanging Sign",
			"Spruce Leaves",
			"Spruce Log",
			"Spruce Planks",
			"Spruce Pressure Plate",
			"Spruce Sapling",
			"Spruce Shelf",
			"Spruce Sign",
			"Spruce Slab",
			"Spruce Stairs",
			"Spruce Trapdoor",
			"Spruce Wall Hanging Sign",
			"Spruce Wall Sign",
			"Spruce Wood",
			"Sticky Piston",
			"Stone",
			"Stone Bricks",
			"Stone Brick Slab",
			"Stone Brick Stairs",
			"Stone Brick Wall",
			"Stone Button",
			"Stonecutter",
			"Stone Pressure Plate",
			"Stone Slab",
			"Stone Stairs",
			"Stripped Acacia Log",
			"Stripped Acacia Wood",
			"Stripped Bamboo Block",
			"Stripped Birch Log",
			"Stripped Birch Wood",
			"Stripped Cherry Log",
			"Stripped Cherry Wood",
			"Stripped Crimson Hyphae",
			"Stripped Crimson Stem",
			"Stripped Dark Oak Log",
			"Stripped Dark Oak Wood",
			"Stripped Jungle Log",
			"Stripped Jungle Wood",
			"Stripped Mangrove Log",
			"Stripped Mangrove Wood",
			"Stripped Oak Log",
			"Stripped Oak Wood",
			"Stripped Pale Oak Log",
			"Stripped Pale Oak Wood",
			"Stripped Spruce Log",
			"Stripped Spruce Wood",
			"Stripped Warped Hyphae",
			"Stripped Warped Stem",
			"Structure Block",
			"Structure Void",
			"Sugar Cane",
			"Sunflower",
			"Suspicious Gravel",
			"Suspicious Sand",
			"Sweet Berry Bush",
			"Tall Dry Grass",
			"Tall Grass",
			"Tall Seagrass",
			"Target",
			"Terracotta",
			"Test Block",
			"Test Instance Block",
			"Tinted Glass",
			"Tnt",
			"Torch",
			"Torchflower",
			"Torchflower Crop",
			"Trapped Chest",
			"Trial Spawner",
			"Tripwire",
			"Tripwire Hook",
			"Tube Coral",
			"Tube Coral Block",
			"Tube Coral Fan",
			"Tube Coral Wall Fan",
			"Tuff",
			"Tuff Bricks",
			"Tuff Brick Slab",
			"Tuff Brick Stairs",
			"Tuff Brick Wall",
			"Tuff Slab",
			"Tuff Stairs",
			"Tuff Wall",
			"Turtle Egg",
			"Twisting Vines",
			"Twisting Vines Plant",
			"Vault",
			"Verdant Froglight",
			"Vine",
			"Void Air",
			"Wall Torch",
			"Warped Button",
			"Warped Door",
			"Warped Fence",
			"Warped Fence Gate",
			"Warped Fungus",
			"Warped Hanging Sign",
			"Warped Hyphae",
			"Warped Nylium",
			"Warped Planks",
			"Warped Pressure Plate",
			"Warped Roots",
			"Warped Shelf",
			"Warped Sign",
			"Warped Slab",
			"Warped Stairs",
			"Warped Stem",
			"Warped Trapdoor",
			"Warped Wall Hanging Sign",
			"Warped Wall Sign",
			"Warped Wart Block",
			"Water",
			"Water Cauldron",
			"Waxed Chiseled Copper",
			"Waxed Copper Bars",
			"Waxed Copper Block",
			"Waxed Copper Bulb",
			"Waxed Copper Chain",
			"Waxed Copper Chest",
			"Waxed Copper Door",
			"Waxed Copper Golem Statue",
			"Waxed Copper Grate",
			"Waxed Copper Lantern",
			"Waxed Copper Trapdoor",
			"Waxed Cut Copper",
			"Waxed Cut Copper Slab",
			"Waxed Cut Copper Stairs",
			"Waxed Exposed Chiseled Copper",
			"Waxed Exposed Copper",
			"Waxed Exposed Copper Bars",
			"Waxed Exposed Copper Bulb",
			"Waxed Exposed Copper Chain",
			"Waxed Exposed Copper Chest",
			"Waxed Exposed Copper Door",
			"Waxed Exposed Copper Golem Statue",
			"Waxed Exposed Copper Grate",
			"Waxed Exposed Copper Lantern",
			"Waxed Exposed Copper Trapdoor",
			"Waxed Exposed Cut Copper",
			"Waxed Exposed Cut Copper Slab",
			"Waxed Exposed Cut Copper Stairs",
			"Waxed Exposed Lightning Rod",
			"Waxed Lightning Rod",
			"Waxed Oxidized Chiseled Copper",
			"Waxed Oxidized Copper",
			"Waxed Oxidized Copper Bars",
			"Waxed Oxidized Copper Bulb",
			"Waxed Oxidized Copper Chain",
			"Waxed Oxidized Copper Chest",
			"Waxed Oxidized Copper Door",
			"Waxed Oxidized Copper Golem Statue",
			"Waxed Oxidized Copper Grate",
			"Waxed Oxidized Copper Lantern",
			"Waxed Oxidized Copper Trapdoor",
			"Waxed Oxidized Cut Copper",
			"Waxed Oxidized Cut Copper Slab",
			"Waxed Oxidized Cut Copper Stairs",
			"Waxed Oxidized Lightning Rod",
			"Waxed Weathered Chiseled Copper",
			"Waxed Weathered Copper",
			"Waxed Weathered Copper Bars",
			"Waxed Weathered Copper Bulb",
			"Waxed Weathered Copper Chain",
			"Waxed Weathered Copper Chest",
			"Waxed Weathered Copper Door",
			"Waxed Weathered Copper Golem Statue",
			"Waxed Weathered Copper Grate",
			"Waxed Weathered Copper Lantern",
			"Waxed Weathered Copper Trapdoor",
			"Waxed Weathered Cut Copper",
			"Waxed Weathered Cut Copper Slab",
			"Waxed Weathered Cut Copper Stairs",
			"Waxed Weathered Lightning Rod",
			"Weathered Chiseled Copper",
			"Weathered Copper",
			"Weathered Copper Bars",
			"Weathered Copper Bulb",
			"Weathered Copper Chain",
			"Weathered Copper Chest",
			"Weathered Copper Door",
			"Weathered Copper Golem Statue",
			"Weathered Copper Grate",
			"Weathered Copper Lantern",
			"Weathered Copper Trapdoor",
			"Weathered Cut Copper",
			"Weathered Cut Copper Slab",
			"Weathered Cut Copper Stairs",
			"Weathered Lightning Rod",
			"Weeping Vines",
			"Weeping Vines Plant",
			"Wet Sponge",
			"Wheat",
			"White Banner",
			"White Bed",
			"White Candle",
			"White Candle Cake",
			"White Carpet",
			"White Concrete",
			"White Concrete Powder",
			"White Glazed Terracotta",
			"White Shulker Box",
			"White Stained Glass",
			"White Stained Glass Pane",
			"White Terracotta",
			"White Tulip",
			"White Wall Banner",
			"White Wool",
			"Wildflowers",
			"Wither Rose",
			"Wither Skeleton Skull",
			"Wither Skeleton Wall Skull",
			"Yellow Banner",
			"Yellow Bed",
			"Yellow Candle",
			"Yellow Candle Cake",
			"Yellow Carpet",
			"Yellow Concrete",
			"Yellow Concrete Powder",
			"Yellow Glazed Terracotta",
			"Yellow Shulker Box",
			"Yellow Stained Glass",
			"Yellow Stained Glass Pane",
			"Yellow Terracotta",
			"Yellow Wall Banner",
			"Yellow Wool",
			"Zombie Head",
			"Zombie Wall Head",
		};

		static const std::unordered_map<std::string, BlockId>& GetNameToId()
		{
			static std::unordered_map<std::string, BlockId> map = []()
			{
				std::unordered_map<std::string, BlockId> m;
				for (size_t i = 0; i < static_cast<size_t>(BlockId::Count); ++i)
					m[s_IdToName[i]] = static_cast<BlockId>(i);
				return m;
			}();
			return map;
		}
	};
} // namespace onion::voxel
